[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-cache = "0.2.2"
nom = "7.1.3"

[lints.clippy]
pedantic = "warn"
